### ISSUE TITLE
Clean-up Mozmill CI after esr45 desupport

### ISSUE THREAD

**Issue by whimboo** [mozilla/mozmill-ci#856]
Given that we do not ship any other ESR45 release we can clean-up our system for the following items:

* [x] Remove all jobs related to esr45 testing (#854)
* [x] Get rid of all the OS X 10.6 machines (#855)
* [x] Enable e10s jobs (issue #601)
* [x] Request decommission of OS X 10.6 Mac Minis (https://bugzilla.mozilla.org/show_bug.cgi?id=1372831)
* [ ] Check if we can easily upgrade Jenkins now given that OS X 10.6 is no longer needed (#573)

**Comment by whimboo** [comment]
The whole system will not live that long anymore. So I'm not investing time in how to get Jenkins upgraded.
